SELECT
    USER_ID,
    NICKNAME,
    CONCAT(UGU.CITY, ' ', UGU.STREET_ADDRESS1, ' ', UGU.STREET_ADDRESS2) 전체주소,
    CONCAT(SUBSTR(UGU.TLNO, 1, 3), '-', SUBSTR(UGU.TLNO, 4, 4),  '-', SUBSTR(UGU.TLNO, 8, 4)) AS 전화번호
FROM USED_GOODS_USER AS UGU
JOIN (
    SELECT WRITER_ID,
    COUNT(*) AS TOTAL_BOARD
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
) AS AL
ON UGU.USER_ID = AL.WRITER_ID
WHERE AL.TOTAL_BOARD > 2
ORDER BY USER_ID DESC